## Put comments here that give an overall description of what your
## functions do

## This protocol will create a matrix that is a user defined object with both
## "data" and operators associated with the data 

## the matrix information will be the parameter passed to the 
##  function makeCacheMatrix()  "x"
## 
## this protocol must be used to create the object for cachesolve() 

makeCacheMatrix <- function(x = matrix()) {
      ## variable to store matrix inverse results - persist within object
      CachedInv <- NULL
      
      ################################
      ## a group of functions that allow calls to:
      ## set and get the matrix to be inversed
      ## set only will work after a call to makeCacheMatrix
      ## set() is not called in this excersize
      
      set <- function(y) {
            x <<- y
            CachedInv <<- NULL
      }
      get <- function() x
      
      ## set and get the inversed function var CachedInv
      setinv <- function(inverse) CachedInv <<- inverse
      getinv <- function() CachedInv
      #################################################
      
      ## returns a list with named members
      list(set = set, get = get, setinv = setinv, getinv = getinv)

}


## Write a short comment describing this function
## this function will calculate the inverse of a matrix
## supplied from object generated by function makeCacheMatrix()
## the calculations will only occur if the object was just initialized and
## the inverse hasn't been calculated and "cached"


##  argumrent x is an matrix/object created with makeCacheMatrix that contains
## the matrix and functions associated with the object
cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
  
      ## check object and use function to retrieve the inverted matrix
      ## or NULL if it has not yet been calculated
  
      matrixInv <- x$getinv()
      
      ## if returned value is not NULL meaning that the inverse has been 
      ## calculated and stored within the object then exit function and return 
      ## inversed matrix
      if (!is.null(matrixInv)){
            message("getting cached data")
            return(matrixInv)
      }
      ## creaate local var and populate with matrix from object x$get call
      mymat.data <- x$get()
      
      ## solve matrix and store in object from makeCacheMatrix (actual cache event)
      matrixInv <- solve(mymat.data,...)
      x$setinv(matrixInv)
      ## return value
      matrixInv
}
